### ISSUE TITLE
a missing folder

### ISSUE THREAD

**Issue by massatt212** [lostalejandro/deckifier#3]
root/usr/share/steamos
[steamos.tar.gz](https://github.com/lostalejandro/deckifier/files/12385134/steamos.tar.gz)

gamescope-session-script
```
# Use SteamOS background if exists
if [ -f "/usr/share/steamos/steamos.png" ] ; then
  export STEAM_UPDATEUI_PNG_BACKGROUND=/usr/share/steamos/steamos.png
fi
```

```
# Use cursor if file exist
if [ -z "$CURSOR_FILE" ] ; then
    CURSOR_FILE="/usr/share/steamos/steamos-cursor.png"
fi
```
Your project is very good, keep it up

**Comment by lostalejandro** [comment]
Hello mate, thanks! After a few months i finally got some free time to made a script, I'll definitely include this.
