### ISSUE TITLE
Change resolution ?

### ISSUE THREAD

**Issue by Tikilou** [lostalejandro/deckifier#4]
It's working without problem on ArchLinux with steamos-compositor-plus AUR installed. (I'm launching in with SteamOS choice in GDM)

In ChimerasOS we can choose any other resolution than 720P, any way to fix it ? :)

**Comment by lostalejandro** [comment]
Hi mate, depending on your hardware it should work with gamescope too, also there is an option in Display settings to set the resolution you want for the current display
