### ISSUE TITLE
Mouse dont work proprealy

### ISSUE THREAD

**Issue by MrDuartePT** [lostalejandro/deckifier#5]
I try mine and your fork and notice that mouse is broken.
In the Steam Deck UI the mouse cursor never apear but if i move the trackpad is behaves like a tumb stick

The trackpad work in the game but the cursor also dont apear.
I also noticed the my usb mouse dont respond to any input.

We should try to see how to solve this. The funny thing is gamescope nested in the desktop the mouse work proprealy (even with force grab)

**Comment by MrDuartePT** [comment]
Even lauching in "Big Picture Mode" (without the -steamdesk) produce the same result

**Comment by lostalejandro** [comment]
Hey there! Sure I'll try my best to solve this. 

First of all, when you say 'trackpad' which device do you mean? I use the trackpad of my Dualsense controller as a mouse without any issues when I'm on the gamescope session. 

Also the invisible cursor could be a missing file i forgot to add in the last commit, another user created an issue with the file. I will try to add it as soon as i can, but for what i understand it could be a hardware/driver related problem.

Please post your hardware here so we can try to identify the issue💪🏼

**Comment by MrDuartePT** [comment]
Hey there!

Well my hardware is a Lenovo Legion 5 gen 6 with Ryzen 7 5800H and RTX 3070, I use the igpu to render gamescope and then use DRI_PRIME=1 in the games launch option. This way i get good performance withouth the weird nvidia problems with gamescope.

I was looking at the code and find that steam change the cusor file name:
![image](https://github.com/lostalejandro/deckifier/assets/68701049/edbfeb30-ae76-4873-94b7-491b2ccee2d6)
I will also update my code and test the new file name.

Edit: this commit in theory fix the mouse i will tested now: 54454f3

About the trackapad, im taliking about the laptop trackpad (i also found that changing the sensitive in the settings change to the laptop trackapd), the only problem is that usb devices dosen't work in that mode (I will try my xbox 360 controller as well), so make impossible to connect at least a mouse.

**Comment by MrDuartePT** [comment]
I also can confirm usb devices works since my usb headset apear in the audio settings. Also my usb Xbox 360 controller work. I was expecting to work since i have xpad compile in my kernel.
![image](https://github.com/lostalejandro/deckifier/assets/68701049/ba315f14-b7d3-4091-8b3f-b6f18ca61196)

**Comment by MrDuartePT** [comment]
Well i can conclude that the cursor only appear when using gamescope in nested mode (inside a wayland compositor) probably for you work since you use a DualSense 4 and kinda emulates the desk control. 
The only thing strange is the lack of cursor inside games and usb mouse dosent work as intended. 
I gonna edit my code to use the cursor inside the icon/valve folder instead of the steam folder b36b911.

Also try to launch inside [cage](https://github.com/cage-kiosk/cage) but dont seems to work 😢 .

At least work well with a controller.

**Comment by MrDuartePT** [comment]
On latest version of steam keybaord and mouse not works properly.
Just need to find a way to set the windows key to open the steam menu
Also see this commit could be usefull for laptop: https://github.com/lostalejandro/deckifier/commit/bf0501e552ec29bfe35ee3b9ac47fad0a6020d2f

Edit: ctr+1/2 also works it open the frist and seconds menus
Night shift dosent work but can be a different program that steam uses.

~~Only mangoapp refuse to work but I can live with that. Regular manhohud work inside the games~~
Mangoapp Work inside the game
![image](https://github.com/lostalejandro/deckifier/assets/68701049/009dbbcd-2c2c-4fa6-8d64-8cb1a05d3cfb)
